### ISSUE TITLE
Questions regard KB and image files

### ISSUE THREAD

**Issue by ArvinZhuang** [wangxw5/wikiDiverse#3]
Hi, thanks for open source the datasets, great work!

I have a few questions regarding the KB used in the paper, I notice that you have an Entity2desc (filtered) file and an Entity2Image file, does these two files are aligned? like all the entities in Entity2desc can be found in Entity2Image as well? or vis versa?
And I also notice that an entity in Entity2Image may have multiple image URLs (sep by [AND]), how can I pick the one to represent the entity?

Thanks in advance!

**Comment by ArvinZhuang** [comment]
Also I notice that the KB size in paper is ~16m, however the num of lines in Entity2desc and Entity2Image seems smaller than that?
`wc -l wikipedia_entity2desc_filtered.tsv.tsv` is 7411987 and `wc -l wikipedia_entity2imgs.tsv.tsv`  is 9094736

**Comment by wangxw5** [comment]
Hi, sorry to reply you so late. Because I've been too busy lately.
1) Entity2desc (filtered) file and Entity2Image file are aligned. But I didn't check whether all the entities in Entity2desc can be found in Entity2Image. Actually, I filtered entity2desc due to its large size. As for entity2image, it is the file containing all the entity2image info we have obtained (for entities we didn't obtain the image info, they are removed from this file.). I use Entity2desc (filtered) as the KB and find its images through Entity2Image. If no image can be found, I will use a all-zero matrix as the image tensor.
2) I use the first image in Entity2Image to present the entity. But if the first image is not available after three requests due to network reasons, I will request the second image instead.

**Comment by ArvinZhuang** [comment]
Hi @wangxw5 , thanks for the reply! it is much clear now. 
Talking about making requests to download images from wiki domains, I'm also trying to do a similar thing but I found it is kind of slow and painful. That would be fantastic if you can share the code that does crawling wiki news/images and Wikipedia descriptions. Really want to learn how you did it!

**Comment by wangxw5** [comment]
We asked a dedicated development engineer to do this. So sorry, I don't have this part of the code.
I will see if I can release the tensor of the images recently.

**Comment by ArvinZhuang** [comment]
No worries! great team work!
